// Code generated by ent, DO NOT EDIT.

package openaiquotaperiod

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the openaiquotaperiod type in the database.
	Label = "open_ai_quota_period"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldResetAt holds the string denoting the reset_at field in the database.
	FieldResetAt = "reset_at"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldUsedUsd holds the string denoting the used_usd field in the database.
	FieldUsedUsd = "used_usd"
	// FieldUsedPercent holds the string denoting the used_percent field in the database.
	FieldUsedPercent = "used_percent"
	// FieldPredictedQuotaUsd holds the string denoting the predicted_quota_usd field in the database.
	FieldPredictedQuotaUsd = "predicted_quota_usd"
	// FieldSnapshotAt holds the string denoting the snapshot_at field in the database.
	FieldSnapshotAt = "snapshot_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the openaiquotaperiod in the database.
	Table = "openai_quota_periods"
)

// Columns holds all SQL columns for openaiquotaperiod fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldStartedAt,
	FieldEndedAt,
	FieldResetAt,
	FieldRequestCount,
	FieldUsedUsd,
	FieldUsedPercent,
	FieldPredictedQuotaUsd,
	FieldSnapshotAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestCount holds the default value on creation for the "request_count" field.
	DefaultRequestCount int64
	// DefaultUsedUsd holds the default value on creation for the "used_usd" field.
	DefaultUsedUsd float64
	// DefaultUsedPercent holds the default value on creation for the "used_percent" field.
	DefaultUsedPercent float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpenAIQuotaPeriod queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByResetAt orders the results by the reset_at field.
func ByResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResetAt, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// ByUsedUsd orders the results by the used_usd field.
func ByUsedUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedUsd, opts...).ToFunc()
}

// ByUsedPercent orders the results by the used_percent field.
func ByUsedPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedPercent, opts...).ToFunc()
}

// ByPredictedQuotaUsd orders the results by the predicted_quota_usd field.
func ByPredictedQuotaUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPredictedQuotaUsd, opts...).ToFunc()
}

// BySnapshotAt orders the results by the snapshot_at field.
func BySnapshotAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSnapshotAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
