// Code generated by ent, DO NOT EDIT.

package openaiquotaperiod

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldAccountID, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldStartedAt, v))
}

// EndedAt applies equality check predicate on the "ended_at" field. It's identical to EndedAtEQ.
func EndedAt(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldEndedAt, v))
}

// ResetAt applies equality check predicate on the "reset_at" field. It's identical to ResetAtEQ.
func ResetAt(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldResetAt, v))
}

// RequestCount applies equality check predicate on the "request_count" field. It's identical to RequestCountEQ.
func RequestCount(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldRequestCount, v))
}

// UsedUsd applies equality check predicate on the "used_usd" field. It's identical to UsedUsdEQ.
func UsedUsd(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldUsedUsd, v))
}

// UsedPercent applies equality check predicate on the "used_percent" field. It's identical to UsedPercentEQ.
func UsedPercent(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldUsedPercent, v))
}

// PredictedQuotaUsd applies equality check predicate on the "predicted_quota_usd" field. It's identical to PredictedQuotaUsdEQ.
func PredictedQuotaUsd(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldPredictedQuotaUsd, v))
}

// SnapshotAt applies equality check predicate on the "snapshot_at" field. It's identical to SnapshotAtEQ.
func SnapshotAt(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldSnapshotAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldAccountID, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldStartedAt, v))
}

// EndedAtEQ applies the EQ predicate on the "ended_at" field.
func EndedAtEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldEndedAt, v))
}

// EndedAtNEQ applies the NEQ predicate on the "ended_at" field.
func EndedAtNEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldEndedAt, v))
}

// EndedAtIn applies the In predicate on the "ended_at" field.
func EndedAtIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldEndedAt, vs...))
}

// EndedAtNotIn applies the NotIn predicate on the "ended_at" field.
func EndedAtNotIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldEndedAt, vs...))
}

// EndedAtGT applies the GT predicate on the "ended_at" field.
func EndedAtGT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldEndedAt, v))
}

// EndedAtGTE applies the GTE predicate on the "ended_at" field.
func EndedAtGTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldEndedAt, v))
}

// EndedAtLT applies the LT predicate on the "ended_at" field.
func EndedAtLT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldEndedAt, v))
}

// EndedAtLTE applies the LTE predicate on the "ended_at" field.
func EndedAtLTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldEndedAt, v))
}

// EndedAtIsNil applies the IsNil predicate on the "ended_at" field.
func EndedAtIsNil() predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIsNull(FieldEndedAt))
}

// EndedAtNotNil applies the NotNil predicate on the "ended_at" field.
func EndedAtNotNil() predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotNull(FieldEndedAt))
}

// ResetAtEQ applies the EQ predicate on the "reset_at" field.
func ResetAtEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldResetAt, v))
}

// ResetAtNEQ applies the NEQ predicate on the "reset_at" field.
func ResetAtNEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldResetAt, v))
}

// ResetAtIn applies the In predicate on the "reset_at" field.
func ResetAtIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldResetAt, vs...))
}

// ResetAtNotIn applies the NotIn predicate on the "reset_at" field.
func ResetAtNotIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldResetAt, vs...))
}

// ResetAtGT applies the GT predicate on the "reset_at" field.
func ResetAtGT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldResetAt, v))
}

// ResetAtGTE applies the GTE predicate on the "reset_at" field.
func ResetAtGTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldResetAt, v))
}

// ResetAtLT applies the LT predicate on the "reset_at" field.
func ResetAtLT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldResetAt, v))
}

// ResetAtLTE applies the LTE predicate on the "reset_at" field.
func ResetAtLTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldResetAt, v))
}

// ResetAtIsNil applies the IsNil predicate on the "reset_at" field.
func ResetAtIsNil() predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIsNull(FieldResetAt))
}

// ResetAtNotNil applies the NotNil predicate on the "reset_at" field.
func ResetAtNotNil() predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotNull(FieldResetAt))
}

// RequestCountEQ applies the EQ predicate on the "request_count" field.
func RequestCountEQ(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldRequestCount, v))
}

// RequestCountNEQ applies the NEQ predicate on the "request_count" field.
func RequestCountNEQ(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldRequestCount, v))
}

// RequestCountIn applies the In predicate on the "request_count" field.
func RequestCountIn(vs ...int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldRequestCount, vs...))
}

// RequestCountNotIn applies the NotIn predicate on the "request_count" field.
func RequestCountNotIn(vs ...int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldRequestCount, vs...))
}

// RequestCountGT applies the GT predicate on the "request_count" field.
func RequestCountGT(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldRequestCount, v))
}

// RequestCountGTE applies the GTE predicate on the "request_count" field.
func RequestCountGTE(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldRequestCount, v))
}

// RequestCountLT applies the LT predicate on the "request_count" field.
func RequestCountLT(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldRequestCount, v))
}

// RequestCountLTE applies the LTE predicate on the "request_count" field.
func RequestCountLTE(v int64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldRequestCount, v))
}

// UsedUsdEQ applies the EQ predicate on the "used_usd" field.
func UsedUsdEQ(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldUsedUsd, v))
}

// UsedUsdNEQ applies the NEQ predicate on the "used_usd" field.
func UsedUsdNEQ(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldUsedUsd, v))
}

// UsedUsdIn applies the In predicate on the "used_usd" field.
func UsedUsdIn(vs ...float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldUsedUsd, vs...))
}

// UsedUsdNotIn applies the NotIn predicate on the "used_usd" field.
func UsedUsdNotIn(vs ...float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldUsedUsd, vs...))
}

// UsedUsdGT applies the GT predicate on the "used_usd" field.
func UsedUsdGT(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldUsedUsd, v))
}

// UsedUsdGTE applies the GTE predicate on the "used_usd" field.
func UsedUsdGTE(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldUsedUsd, v))
}

// UsedUsdLT applies the LT predicate on the "used_usd" field.
func UsedUsdLT(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldUsedUsd, v))
}

// UsedUsdLTE applies the LTE predicate on the "used_usd" field.
func UsedUsdLTE(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldUsedUsd, v))
}

// UsedPercentEQ applies the EQ predicate on the "used_percent" field.
func UsedPercentEQ(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldUsedPercent, v))
}

// UsedPercentNEQ applies the NEQ predicate on the "used_percent" field.
func UsedPercentNEQ(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldUsedPercent, v))
}

// UsedPercentIn applies the In predicate on the "used_percent" field.
func UsedPercentIn(vs ...float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldUsedPercent, vs...))
}

// UsedPercentNotIn applies the NotIn predicate on the "used_percent" field.
func UsedPercentNotIn(vs ...float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldUsedPercent, vs...))
}

// UsedPercentGT applies the GT predicate on the "used_percent" field.
func UsedPercentGT(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldUsedPercent, v))
}

// UsedPercentGTE applies the GTE predicate on the "used_percent" field.
func UsedPercentGTE(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldUsedPercent, v))
}

// UsedPercentLT applies the LT predicate on the "used_percent" field.
func UsedPercentLT(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldUsedPercent, v))
}

// UsedPercentLTE applies the LTE predicate on the "used_percent" field.
func UsedPercentLTE(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldUsedPercent, v))
}

// PredictedQuotaUsdEQ applies the EQ predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdEQ(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldPredictedQuotaUsd, v))
}

// PredictedQuotaUsdNEQ applies the NEQ predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdNEQ(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldPredictedQuotaUsd, v))
}

// PredictedQuotaUsdIn applies the In predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdIn(vs ...float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldPredictedQuotaUsd, vs...))
}

// PredictedQuotaUsdNotIn applies the NotIn predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdNotIn(vs ...float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldPredictedQuotaUsd, vs...))
}

// PredictedQuotaUsdGT applies the GT predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdGT(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldPredictedQuotaUsd, v))
}

// PredictedQuotaUsdGTE applies the GTE predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdGTE(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldPredictedQuotaUsd, v))
}

// PredictedQuotaUsdLT applies the LT predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdLT(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldPredictedQuotaUsd, v))
}

// PredictedQuotaUsdLTE applies the LTE predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdLTE(v float64) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldPredictedQuotaUsd, v))
}

// PredictedQuotaUsdIsNil applies the IsNil predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdIsNil() predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIsNull(FieldPredictedQuotaUsd))
}

// PredictedQuotaUsdNotNil applies the NotNil predicate on the "predicted_quota_usd" field.
func PredictedQuotaUsdNotNil() predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotNull(FieldPredictedQuotaUsd))
}

// SnapshotAtEQ applies the EQ predicate on the "snapshot_at" field.
func SnapshotAtEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldSnapshotAt, v))
}

// SnapshotAtNEQ applies the NEQ predicate on the "snapshot_at" field.
func SnapshotAtNEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldSnapshotAt, v))
}

// SnapshotAtIn applies the In predicate on the "snapshot_at" field.
func SnapshotAtIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldSnapshotAt, vs...))
}

// SnapshotAtNotIn applies the NotIn predicate on the "snapshot_at" field.
func SnapshotAtNotIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldSnapshotAt, vs...))
}

// SnapshotAtGT applies the GT predicate on the "snapshot_at" field.
func SnapshotAtGT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldSnapshotAt, v))
}

// SnapshotAtGTE applies the GTE predicate on the "snapshot_at" field.
func SnapshotAtGTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldSnapshotAt, v))
}

// SnapshotAtLT applies the LT predicate on the "snapshot_at" field.
func SnapshotAtLT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldSnapshotAt, v))
}

// SnapshotAtLTE applies the LTE predicate on the "snapshot_at" field.
func SnapshotAtLTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldSnapshotAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIQuotaPeriod) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIQuotaPeriod) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIQuotaPeriod) predicate.OpenAIQuotaPeriod {
	return predicate.OpenAIQuotaPeriod(sql.NotPredicates(p))
}
