// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/openaiquotaperiod"
)

// OpenAIQuotaPeriod is the model entity for the OpenAIQuotaPeriod schema.
type OpenAIQuotaPeriod struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// EndedAt holds the value of the "ended_at" field.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// ResetAt holds the value of the "reset_at" field.
	ResetAt *time.Time `json:"reset_at,omitempty"`
	// RequestCount holds the value of the "request_count" field.
	RequestCount int64 `json:"request_count,omitempty"`
	// UsedUsd holds the value of the "used_usd" field.
	UsedUsd float64 `json:"used_usd,omitempty"`
	// UsedPercent holds the value of the "used_percent" field.
	UsedPercent float64 `json:"used_percent,omitempty"`
	// PredictedQuotaUsd holds the value of the "predicted_quota_usd" field.
	PredictedQuotaUsd *float64 `json:"predicted_quota_usd,omitempty"`
	// SnapshotAt holds the value of the "snapshot_at" field.
	SnapshotAt time.Time `json:"snapshot_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIQuotaPeriod) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaiquotaperiod.FieldUsedUsd, openaiquotaperiod.FieldUsedPercent, openaiquotaperiod.FieldPredictedQuotaUsd:
			values[i] = new(sql.NullFloat64)
		case openaiquotaperiod.FieldID, openaiquotaperiod.FieldAccountID, openaiquotaperiod.FieldRequestCount:
			values[i] = new(sql.NullInt64)
		case openaiquotaperiod.FieldStartedAt, openaiquotaperiod.FieldEndedAt, openaiquotaperiod.FieldResetAt, openaiquotaperiod.FieldSnapshotAt, openaiquotaperiod.FieldCreatedAt, openaiquotaperiod.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIQuotaPeriod fields.
func (_m *OpenAIQuotaPeriod) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaiquotaperiod.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaiquotaperiod.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaiquotaperiod.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case openaiquotaperiod.FieldEndedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ended_at", values[i])
			} else if value.Valid {
				_m.EndedAt = new(time.Time)
				*_m.EndedAt = value.Time
			}
		case openaiquotaperiod.FieldResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reset_at", values[i])
			} else if value.Valid {
				_m.ResetAt = new(time.Time)
				*_m.ResetAt = value.Time
			}
		case openaiquotaperiod.FieldRequestCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_count", values[i])
			} else if value.Valid {
				_m.RequestCount = value.Int64
			}
		case openaiquotaperiod.FieldUsedUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_usd", values[i])
			} else if value.Valid {
				_m.UsedUsd = value.Float64
			}
		case openaiquotaperiod.FieldUsedPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_percent", values[i])
			} else if value.Valid {
				_m.UsedPercent = value.Float64
			}
		case openaiquotaperiod.FieldPredictedQuotaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field predicted_quota_usd", values[i])
			} else if value.Valid {
				_m.PredictedQuotaUsd = new(float64)
				*_m.PredictedQuotaUsd = value.Float64
			}
		case openaiquotaperiod.FieldSnapshotAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_at", values[i])
			} else if value.Valid {
				_m.SnapshotAt = value.Time
			}
		case openaiquotaperiod.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaiquotaperiod.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIQuotaPeriod.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIQuotaPeriod) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OpenAIQuotaPeriod.
// Note that you need to call OpenAIQuotaPeriod.Unwrap() before calling this method if this OpenAIQuotaPeriod
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIQuotaPeriod) Update() *OpenAIQuotaPeriodUpdateOne {
	return NewOpenAIQuotaPeriodClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIQuotaPeriod entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIQuotaPeriod) Unwrap() *OpenAIQuotaPeriod {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIQuotaPeriod is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIQuotaPeriod) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIQuotaPeriod(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.EndedAt; v != nil {
		builder.WriteString("ended_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResetAt; v != nil {
		builder.WriteString("reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("request_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestCount))
	builder.WriteString(", ")
	builder.WriteString("used_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedUsd))
	builder.WriteString(", ")
	builder.WriteString("used_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedPercent))
	builder.WriteString(", ")
	if v := _m.PredictedQuotaUsd; v != nil {
		builder.WriteString("predicted_quota_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("snapshot_at=")
	builder.WriteString(_m.SnapshotAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIQuotaPeriods is a parsable slice of OpenAIQuotaPeriod.
type OpenAIQuotaPeriods []*OpenAIQuotaPeriod
