// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaiquotaperiod"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIQuotaPeriodDelete is the builder for deleting a OpenAIQuotaPeriod entity.
type OpenAIQuotaPeriodDelete struct {
	config
	hooks    []Hook
	mutation *OpenAIQuotaPeriodMutation
}

// Where appends a list predicates to the OpenAIQuotaPeriodDelete builder.
func (_d *OpenAIQuotaPeriodDelete) Where(ps ...predicate.OpenAIQuotaPeriod) *OpenAIQuotaPeriodDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAIQuotaPeriodDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIQuotaPeriodDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAIQuotaPeriodDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openaiquotaperiod.Table, sqlgraph.NewFieldSpec(openaiquotaperiod.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAIQuotaPeriodDeleteOne is the builder for deleting a single OpenAIQuotaPeriod entity.
type OpenAIQuotaPeriodDeleteOne struct {
	_d *OpenAIQuotaPeriodDelete
}

// Where appends a list predicates to the OpenAIQuotaPeriodDelete builder.
func (_d *OpenAIQuotaPeriodDeleteOne) Where(ps ...predicate.OpenAIQuotaPeriod) *OpenAIQuotaPeriodDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAIQuotaPeriodDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openaiquotaperiod.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIQuotaPeriodDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
