// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaiquotaperiod"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// OpenAIQuotaPeriodUpdate is the builder for updating OpenAIQuotaPeriod entities.
type OpenAIQuotaPeriodUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIQuotaPeriodMutation
}

// Where appends a list predicates to the OpenAIQuotaPeriodUpdate builder.
func (_u *OpenAIQuotaPeriodUpdate) Where(ps ...predicate.OpenAIQuotaPeriod) *OpenAIQuotaPeriodUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIQuotaPeriodUpdate) SetAccountID(v int64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableAccountID(v *int64) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIQuotaPeriodUpdate) AddAccountID(v int64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *OpenAIQuotaPeriodUpdate) SetStartedAt(v time.Time) *OpenAIQuotaPeriodUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableStartedAt(v *time.Time) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *OpenAIQuotaPeriodUpdate) SetEndedAt(v time.Time) *OpenAIQuotaPeriodUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableEndedAt(v *time.Time) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *OpenAIQuotaPeriodUpdate) ClearEndedAt() *OpenAIQuotaPeriodUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *OpenAIQuotaPeriodUpdate) SetResetAt(v time.Time) *OpenAIQuotaPeriodUpdate {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableResetAt(v *time.Time) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *OpenAIQuotaPeriodUpdate) ClearResetAt() *OpenAIQuotaPeriodUpdate {
	_u.mutation.ClearResetAt()
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *OpenAIQuotaPeriodUpdate) SetRequestCount(v int64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableRequestCount(v *int64) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *OpenAIQuotaPeriodUpdate) AddRequestCount(v int64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetTokenCount sets the "token_count" field.
func (_u *OpenAIQuotaPeriodUpdate) SetTokenCount(v int64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.ResetTokenCount()
	_u.mutation.SetTokenCount(v)
	return _u
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableTokenCount(v *int64) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetTokenCount(*v)
	}
	return _u
}

// AddTokenCount adds value to the "token_count" field.
func (_u *OpenAIQuotaPeriodUpdate) AddTokenCount(v int64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.AddTokenCount(v)
	return _u
}

// ClearTokenCount clears the value of the "token_count" field.
func (_u *OpenAIQuotaPeriodUpdate) ClearTokenCount() *OpenAIQuotaPeriodUpdate {
	_u.mutation.ClearTokenCount()
	return _u
}

// SetUsedUsd sets the "used_usd" field.
func (_u *OpenAIQuotaPeriodUpdate) SetUsedUsd(v float64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.ResetUsedUsd()
	_u.mutation.SetUsedUsd(v)
	return _u
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableUsedUsd(v *float64) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetUsedUsd(*v)
	}
	return _u
}

// AddUsedUsd adds value to the "used_usd" field.
func (_u *OpenAIQuotaPeriodUpdate) AddUsedUsd(v float64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.AddUsedUsd(v)
	return _u
}

// SetUsedPercent sets the "used_percent" field.
func (_u *OpenAIQuotaPeriodUpdate) SetUsedPercent(v float64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.ResetUsedPercent()
	_u.mutation.SetUsedPercent(v)
	return _u
}

// SetNillableUsedPercent sets the "used_percent" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableUsedPercent(v *float64) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetUsedPercent(*v)
	}
	return _u
}

// AddUsedPercent adds value to the "used_percent" field.
func (_u *OpenAIQuotaPeriodUpdate) AddUsedPercent(v float64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.AddUsedPercent(v)
	return _u
}

// SetPredictedQuotaUsd sets the "predicted_quota_usd" field.
func (_u *OpenAIQuotaPeriodUpdate) SetPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.ResetPredictedQuotaUsd()
	_u.mutation.SetPredictedQuotaUsd(v)
	return _u
}

// SetNillablePredictedQuotaUsd sets the "predicted_quota_usd" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillablePredictedQuotaUsd(v *float64) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetPredictedQuotaUsd(*v)
	}
	return _u
}

// AddPredictedQuotaUsd adds value to the "predicted_quota_usd" field.
func (_u *OpenAIQuotaPeriodUpdate) AddPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpdate {
	_u.mutation.AddPredictedQuotaUsd(v)
	return _u
}

// ClearPredictedQuotaUsd clears the value of the "predicted_quota_usd" field.
func (_u *OpenAIQuotaPeriodUpdate) ClearPredictedQuotaUsd() *OpenAIQuotaPeriodUpdate {
	_u.mutation.ClearPredictedQuotaUsd()
	return _u
}

// SetSnapshotAt sets the "snapshot_at" field.
func (_u *OpenAIQuotaPeriodUpdate) SetSnapshotAt(v time.Time) *OpenAIQuotaPeriodUpdate {
	_u.mutation.SetSnapshotAt(v)
	return _u
}

// SetNillableSnapshotAt sets the "snapshot_at" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdate) SetNillableSnapshotAt(v *time.Time) *OpenAIQuotaPeriodUpdate {
	if v != nil {
		_u.SetSnapshotAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIQuotaPeriodUpdate) SetUpdatedAt(v time.Time) *OpenAIQuotaPeriodUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAIQuotaPeriodMutation object of the builder.
func (_u *OpenAIQuotaPeriodUpdate) Mutation() *OpenAIQuotaPeriodMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIQuotaPeriodUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIQuotaPeriodUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIQuotaPeriodUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIQuotaPeriodUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIQuotaPeriodUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaiquotaperiod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OpenAIQuotaPeriodUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(openaiquotaperiod.Table, openaiquotaperiod.Columns, sqlgraph.NewFieldSpec(openaiquotaperiod.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaiquotaperiod.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaiquotaperiod.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(openaiquotaperiod.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(openaiquotaperiod.FieldResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(openaiquotaperiod.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(openaiquotaperiod.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TokenCount(); ok {
		_spec.SetField(openaiquotaperiod.FieldTokenCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenCount(); ok {
		_spec.AddField(openaiquotaperiod.FieldTokenCount, field.TypeInt64, value)
	}
	if _u.mutation.TokenCountCleared() {
		_spec.ClearField(openaiquotaperiod.FieldTokenCount, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsedUsd(); ok {
		_spec.SetField(openaiquotaperiod.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedUsd(); ok {
		_spec.AddField(openaiquotaperiod.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedPercent(); ok {
		_spec.SetField(openaiquotaperiod.FieldUsedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedPercent(); ok {
		_spec.AddField(openaiquotaperiod.FieldUsedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PredictedQuotaUsd(); ok {
		_spec.SetField(openaiquotaperiod.FieldPredictedQuotaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPredictedQuotaUsd(); ok {
		_spec.AddField(openaiquotaperiod.FieldPredictedQuotaUsd, field.TypeFloat64, value)
	}
	if _u.mutation.PredictedQuotaUsdCleared() {
		_spec.ClearField(openaiquotaperiod.FieldPredictedQuotaUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SnapshotAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldSnapshotAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaiquotaperiod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIQuotaPeriodUpdateOne is the builder for updating a single OpenAIQuotaPeriod entity.
type OpenAIQuotaPeriodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIQuotaPeriodMutation
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetAccountID(v int64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableAccountID(v *int64) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *OpenAIQuotaPeriodUpdateOne) AddAccountID(v int64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetStartedAt(v time.Time) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableStartedAt(v *time.Time) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetEndedAt(v time.Time) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableEndedAt(v *time.Time) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *OpenAIQuotaPeriodUpdateOne) ClearEndedAt() *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetResetAt(v time.Time) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableResetAt(v *time.Time) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *OpenAIQuotaPeriodUpdateOne) ClearResetAt() *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ClearResetAt()
	return _u
}

// SetRequestCount sets the "request_count" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetRequestCount(v int64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ResetRequestCount()
	_u.mutation.SetRequestCount(v)
	return _u
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableRequestCount(v *int64) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetRequestCount(*v)
	}
	return _u
}

// AddRequestCount adds value to the "request_count" field.
func (_u *OpenAIQuotaPeriodUpdateOne) AddRequestCount(v int64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.AddRequestCount(v)
	return _u
}

// SetTokenCount sets the "token_count" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetTokenCount(v int64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ResetTokenCount()
	_u.mutation.SetTokenCount(v)
	return _u
}

// SetNillableTokenCount sets the "token_count" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableTokenCount(v *int64) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetTokenCount(*v)
	}
	return _u
}

// AddTokenCount adds value to the "token_count" field.
func (_u *OpenAIQuotaPeriodUpdateOne) AddTokenCount(v int64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.AddTokenCount(v)
	return _u
}

// ClearTokenCount clears the value of the "token_count" field.
func (_u *OpenAIQuotaPeriodUpdateOne) ClearTokenCount() *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ClearTokenCount()
	return _u
}

// SetUsedUsd sets the "used_usd" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetUsedUsd(v float64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ResetUsedUsd()
	_u.mutation.SetUsedUsd(v)
	return _u
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableUsedUsd(v *float64) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetUsedUsd(*v)
	}
	return _u
}

// AddUsedUsd adds value to the "used_usd" field.
func (_u *OpenAIQuotaPeriodUpdateOne) AddUsedUsd(v float64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.AddUsedUsd(v)
	return _u
}

// SetUsedPercent sets the "used_percent" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetUsedPercent(v float64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ResetUsedPercent()
	_u.mutation.SetUsedPercent(v)
	return _u
}

// SetNillableUsedPercent sets the "used_percent" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableUsedPercent(v *float64) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetUsedPercent(*v)
	}
	return _u
}

// AddUsedPercent adds value to the "used_percent" field.
func (_u *OpenAIQuotaPeriodUpdateOne) AddUsedPercent(v float64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.AddUsedPercent(v)
	return _u
}

// SetPredictedQuotaUsd sets the "predicted_quota_usd" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ResetPredictedQuotaUsd()
	_u.mutation.SetPredictedQuotaUsd(v)
	return _u
}

// SetNillablePredictedQuotaUsd sets the "predicted_quota_usd" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillablePredictedQuotaUsd(v *float64) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetPredictedQuotaUsd(*v)
	}
	return _u
}

// AddPredictedQuotaUsd adds value to the "predicted_quota_usd" field.
func (_u *OpenAIQuotaPeriodUpdateOne) AddPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.AddPredictedQuotaUsd(v)
	return _u
}

// ClearPredictedQuotaUsd clears the value of the "predicted_quota_usd" field.
func (_u *OpenAIQuotaPeriodUpdateOne) ClearPredictedQuotaUsd() *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.ClearPredictedQuotaUsd()
	return _u
}

// SetSnapshotAt sets the "snapshot_at" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetSnapshotAt(v time.Time) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.SetSnapshotAt(v)
	return _u
}

// SetNillableSnapshotAt sets the "snapshot_at" field if the given value is not nil.
func (_u *OpenAIQuotaPeriodUpdateOne) SetNillableSnapshotAt(v *time.Time) *OpenAIQuotaPeriodUpdateOne {
	if v != nil {
		_u.SetSnapshotAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIQuotaPeriodUpdateOne) SetUpdatedAt(v time.Time) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OpenAIQuotaPeriodMutation object of the builder.
func (_u *OpenAIQuotaPeriodUpdateOne) Mutation() *OpenAIQuotaPeriodMutation {
	return _u.mutation
}

// Where appends a list predicates to the OpenAIQuotaPeriodUpdate builder.
func (_u *OpenAIQuotaPeriodUpdateOne) Where(ps ...predicate.OpenAIQuotaPeriod) *OpenAIQuotaPeriodUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIQuotaPeriodUpdateOne) Select(field string, fields ...string) *OpenAIQuotaPeriodUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIQuotaPeriod entity.
func (_u *OpenAIQuotaPeriodUpdateOne) Save(ctx context.Context) (*OpenAIQuotaPeriod, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIQuotaPeriodUpdateOne) SaveX(ctx context.Context) *OpenAIQuotaPeriod {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIQuotaPeriodUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIQuotaPeriodUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIQuotaPeriodUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaiquotaperiod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *OpenAIQuotaPeriodUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIQuotaPeriod, err error) {
	_spec := sqlgraph.NewUpdateSpec(openaiquotaperiod.Table, openaiquotaperiod.Columns, sqlgraph.NewFieldSpec(openaiquotaperiod.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIQuotaPeriod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaiquotaperiod.FieldID)
		for _, f := range fields {
			if !openaiquotaperiod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaiquotaperiod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(openaiquotaperiod.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(openaiquotaperiod.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(openaiquotaperiod.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(openaiquotaperiod.FieldResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RequestCount(); ok {
		_spec.SetField(openaiquotaperiod.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestCount(); ok {
		_spec.AddField(openaiquotaperiod.FieldRequestCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TokenCount(); ok {
		_spec.SetField(openaiquotaperiod.FieldTokenCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenCount(); ok {
		_spec.AddField(openaiquotaperiod.FieldTokenCount, field.TypeInt64, value)
	}
	if _u.mutation.TokenCountCleared() {
		_spec.ClearField(openaiquotaperiod.FieldTokenCount, field.TypeInt64)
	}
	if value, ok := _u.mutation.UsedUsd(); ok {
		_spec.SetField(openaiquotaperiod.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedUsd(); ok {
		_spec.AddField(openaiquotaperiod.FieldUsedUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsedPercent(); ok {
		_spec.SetField(openaiquotaperiod.FieldUsedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsedPercent(); ok {
		_spec.AddField(openaiquotaperiod.FieldUsedPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PredictedQuotaUsd(); ok {
		_spec.SetField(openaiquotaperiod.FieldPredictedQuotaUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPredictedQuotaUsd(); ok {
		_spec.AddField(openaiquotaperiod.FieldPredictedQuotaUsd, field.TypeFloat64, value)
	}
	if _u.mutation.PredictedQuotaUsdCleared() {
		_spec.ClearField(openaiquotaperiod.FieldPredictedQuotaUsd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SnapshotAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldSnapshotAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OpenAIQuotaPeriod{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaiquotaperiod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
