// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/openaiquotaperiod"
)

// OpenAIQuotaPeriodCreate is the builder for creating a OpenAIQuotaPeriod entity.
type OpenAIQuotaPeriodCreate struct {
	config
	mutation *OpenAIQuotaPeriodMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *OpenAIQuotaPeriodCreate) SetAccountID(v int64) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *OpenAIQuotaPeriodCreate) SetStartedAt(v time.Time) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *OpenAIQuotaPeriodCreate) SetEndedAt(v time.Time) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *OpenAIQuotaPeriodCreate) SetNillableEndedAt(v *time.Time) *OpenAIQuotaPeriodCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetResetAt sets the "reset_at" field.
func (_c *OpenAIQuotaPeriodCreate) SetResetAt(v time.Time) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetResetAt(v)
	return _c
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_c *OpenAIQuotaPeriodCreate) SetNillableResetAt(v *time.Time) *OpenAIQuotaPeriodCreate {
	if v != nil {
		_c.SetResetAt(*v)
	}
	return _c
}

// SetRequestCount sets the "request_count" field.
func (_c *OpenAIQuotaPeriodCreate) SetRequestCount(v int64) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetRequestCount(v)
	return _c
}

// SetNillableRequestCount sets the "request_count" field if the given value is not nil.
func (_c *OpenAIQuotaPeriodCreate) SetNillableRequestCount(v *int64) *OpenAIQuotaPeriodCreate {
	if v != nil {
		_c.SetRequestCount(*v)
	}
	return _c
}

// SetUsedUsd sets the "used_usd" field.
func (_c *OpenAIQuotaPeriodCreate) SetUsedUsd(v float64) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetUsedUsd(v)
	return _c
}

// SetNillableUsedUsd sets the "used_usd" field if the given value is not nil.
func (_c *OpenAIQuotaPeriodCreate) SetNillableUsedUsd(v *float64) *OpenAIQuotaPeriodCreate {
	if v != nil {
		_c.SetUsedUsd(*v)
	}
	return _c
}

// SetUsedPercent sets the "used_percent" field.
func (_c *OpenAIQuotaPeriodCreate) SetUsedPercent(v float64) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetUsedPercent(v)
	return _c
}

// SetNillableUsedPercent sets the "used_percent" field if the given value is not nil.
func (_c *OpenAIQuotaPeriodCreate) SetNillableUsedPercent(v *float64) *OpenAIQuotaPeriodCreate {
	if v != nil {
		_c.SetUsedPercent(*v)
	}
	return _c
}

// SetPredictedQuotaUsd sets the "predicted_quota_usd" field.
func (_c *OpenAIQuotaPeriodCreate) SetPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetPredictedQuotaUsd(v)
	return _c
}

// SetNillablePredictedQuotaUsd sets the "predicted_quota_usd" field if the given value is not nil.
func (_c *OpenAIQuotaPeriodCreate) SetNillablePredictedQuotaUsd(v *float64) *OpenAIQuotaPeriodCreate {
	if v != nil {
		_c.SetPredictedQuotaUsd(*v)
	}
	return _c
}

// SetSnapshotAt sets the "snapshot_at" field.
func (_c *OpenAIQuotaPeriodCreate) SetSnapshotAt(v time.Time) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetSnapshotAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAIQuotaPeriodCreate) SetCreatedAt(v time.Time) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAIQuotaPeriodCreate) SetNillableCreatedAt(v *time.Time) *OpenAIQuotaPeriodCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAIQuotaPeriodCreate) SetUpdatedAt(v time.Time) *OpenAIQuotaPeriodCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAIQuotaPeriodCreate) SetNillableUpdatedAt(v *time.Time) *OpenAIQuotaPeriodCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the OpenAIQuotaPeriodMutation object of the builder.
func (_c *OpenAIQuotaPeriodCreate) Mutation() *OpenAIQuotaPeriodMutation {
	return _c.mutation
}

// Save creates the OpenAIQuotaPeriod in the database.
func (_c *OpenAIQuotaPeriodCreate) Save(ctx context.Context) (*OpenAIQuotaPeriod, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAIQuotaPeriodCreate) SaveX(ctx context.Context) *OpenAIQuotaPeriod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIQuotaPeriodCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIQuotaPeriodCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAIQuotaPeriodCreate) defaults() {
	if _, ok := _c.mutation.RequestCount(); !ok {
		v := openaiquotaperiod.DefaultRequestCount
		_c.mutation.SetRequestCount(v)
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		v := openaiquotaperiod.DefaultUsedUsd
		_c.mutation.SetUsedUsd(v)
	}
	if _, ok := _c.mutation.UsedPercent(); !ok {
		v := openaiquotaperiod.DefaultUsedPercent
		_c.mutation.SetUsedPercent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openaiquotaperiod.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openaiquotaperiod.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAIQuotaPeriodCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OpenAIQuotaPeriod.account_id"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "OpenAIQuotaPeriod.started_at"`)}
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		return &ValidationError{Name: "request_count", err: errors.New(`ent: missing required field "OpenAIQuotaPeriod.request_count"`)}
	}
	if _, ok := _c.mutation.UsedUsd(); !ok {
		return &ValidationError{Name: "used_usd", err: errors.New(`ent: missing required field "OpenAIQuotaPeriod.used_usd"`)}
	}
	if _, ok := _c.mutation.UsedPercent(); !ok {
		return &ValidationError{Name: "used_percent", err: errors.New(`ent: missing required field "OpenAIQuotaPeriod.used_percent"`)}
	}
	if _, ok := _c.mutation.SnapshotAt(); !ok {
		return &ValidationError{Name: "snapshot_at", err: errors.New(`ent: missing required field "OpenAIQuotaPeriod.snapshot_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAIQuotaPeriod.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAIQuotaPeriod.updated_at"`)}
	}
	return nil
}

func (_c *OpenAIQuotaPeriodCreate) sqlSave(ctx context.Context) (*OpenAIQuotaPeriod, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAIQuotaPeriodCreate) createSpec() (*OpenAIQuotaPeriod, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAIQuotaPeriod{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openaiquotaperiod.Table, sqlgraph.NewFieldSpec(openaiquotaperiod.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(openaiquotaperiod.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.ResetAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldResetAt, field.TypeTime, value)
		_node.ResetAt = &value
	}
	if value, ok := _c.mutation.RequestCount(); ok {
		_spec.SetField(openaiquotaperiod.FieldRequestCount, field.TypeInt64, value)
		_node.RequestCount = value
	}
	if value, ok := _c.mutation.UsedUsd(); ok {
		_spec.SetField(openaiquotaperiod.FieldUsedUsd, field.TypeFloat64, value)
		_node.UsedUsd = value
	}
	if value, ok := _c.mutation.UsedPercent(); ok {
		_spec.SetField(openaiquotaperiod.FieldUsedPercent, field.TypeFloat64, value)
		_node.UsedPercent = value
	}
	if value, ok := _c.mutation.PredictedQuotaUsd(); ok {
		_spec.SetField(openaiquotaperiod.FieldPredictedQuotaUsd, field.TypeFloat64, value)
		_node.PredictedQuotaUsd = &value
	}
	if value, ok := _c.mutation.SnapshotAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldSnapshotAt, field.TypeTime, value)
		_node.SnapshotAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openaiquotaperiod.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIQuotaPeriod.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIQuotaPeriodUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIQuotaPeriodCreate) OnConflict(opts ...sql.ConflictOption) *OpenAIQuotaPeriodUpsertOne {
	_c.conflict = opts
	return &OpenAIQuotaPeriodUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIQuotaPeriod.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIQuotaPeriodCreate) OnConflictColumns(columns ...string) *OpenAIQuotaPeriodUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIQuotaPeriodUpsertOne{
		create: _c,
	}
}

type (
	// OpenAIQuotaPeriodUpsertOne is the builder for "upsert"-ing
	//  one OpenAIQuotaPeriod node.
	OpenAIQuotaPeriodUpsertOne struct {
		create *OpenAIQuotaPeriodCreate
	}

	// OpenAIQuotaPeriodUpsert is the "OnConflict" setter.
	OpenAIQuotaPeriodUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *OpenAIQuotaPeriodUpsert) SetAccountID(v int64) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateAccountID() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIQuotaPeriodUpsert) AddAccountID(v int64) *OpenAIQuotaPeriodUpsert {
	u.Add(openaiquotaperiod.FieldAccountID, v)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAIQuotaPeriodUpsert) SetStartedAt(v time.Time) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateStartedAt() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldStartedAt)
	return u
}

// SetEndedAt sets the "ended_at" field.
func (u *OpenAIQuotaPeriodUpsert) SetEndedAt(v time.Time) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldEndedAt, v)
	return u
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateEndedAt() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldEndedAt)
	return u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *OpenAIQuotaPeriodUpsert) ClearEndedAt() *OpenAIQuotaPeriodUpsert {
	u.SetNull(openaiquotaperiod.FieldEndedAt)
	return u
}

// SetResetAt sets the "reset_at" field.
func (u *OpenAIQuotaPeriodUpsert) SetResetAt(v time.Time) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldResetAt, v)
	return u
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateResetAt() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldResetAt)
	return u
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *OpenAIQuotaPeriodUpsert) ClearResetAt() *OpenAIQuotaPeriodUpsert {
	u.SetNull(openaiquotaperiod.FieldResetAt)
	return u
}

// SetRequestCount sets the "request_count" field.
func (u *OpenAIQuotaPeriodUpsert) SetRequestCount(v int64) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldRequestCount, v)
	return u
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateRequestCount() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldRequestCount)
	return u
}

// AddRequestCount adds v to the "request_count" field.
func (u *OpenAIQuotaPeriodUpsert) AddRequestCount(v int64) *OpenAIQuotaPeriodUpsert {
	u.Add(openaiquotaperiod.FieldRequestCount, v)
	return u
}

// SetUsedUsd sets the "used_usd" field.
func (u *OpenAIQuotaPeriodUpsert) SetUsedUsd(v float64) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldUsedUsd, v)
	return u
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateUsedUsd() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldUsedUsd)
	return u
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *OpenAIQuotaPeriodUpsert) AddUsedUsd(v float64) *OpenAIQuotaPeriodUpsert {
	u.Add(openaiquotaperiod.FieldUsedUsd, v)
	return u
}

// SetUsedPercent sets the "used_percent" field.
func (u *OpenAIQuotaPeriodUpsert) SetUsedPercent(v float64) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldUsedPercent, v)
	return u
}

// UpdateUsedPercent sets the "used_percent" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateUsedPercent() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldUsedPercent)
	return u
}

// AddUsedPercent adds v to the "used_percent" field.
func (u *OpenAIQuotaPeriodUpsert) AddUsedPercent(v float64) *OpenAIQuotaPeriodUpsert {
	u.Add(openaiquotaperiod.FieldUsedPercent, v)
	return u
}

// SetPredictedQuotaUsd sets the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsert) SetPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldPredictedQuotaUsd, v)
	return u
}

// UpdatePredictedQuotaUsd sets the "predicted_quota_usd" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdatePredictedQuotaUsd() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldPredictedQuotaUsd)
	return u
}

// AddPredictedQuotaUsd adds v to the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsert) AddPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpsert {
	u.Add(openaiquotaperiod.FieldPredictedQuotaUsd, v)
	return u
}

// ClearPredictedQuotaUsd clears the value of the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsert) ClearPredictedQuotaUsd() *OpenAIQuotaPeriodUpsert {
	u.SetNull(openaiquotaperiod.FieldPredictedQuotaUsd)
	return u
}

// SetSnapshotAt sets the "snapshot_at" field.
func (u *OpenAIQuotaPeriodUpsert) SetSnapshotAt(v time.Time) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldSnapshotAt, v)
	return u
}

// UpdateSnapshotAt sets the "snapshot_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateSnapshotAt() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldSnapshotAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIQuotaPeriodUpsert) SetUpdatedAt(v time.Time) *OpenAIQuotaPeriodUpsert {
	u.Set(openaiquotaperiod.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsert) UpdateUpdatedAt() *OpenAIQuotaPeriodUpsert {
	u.SetExcluded(openaiquotaperiod.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAIQuotaPeriod.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIQuotaPeriodUpsertOne) UpdateNewValues() *OpenAIQuotaPeriodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openaiquotaperiod.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIQuotaPeriod.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAIQuotaPeriodUpsertOne) Ignore() *OpenAIQuotaPeriodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIQuotaPeriodUpsertOne) DoNothing() *OpenAIQuotaPeriodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIQuotaPeriodCreate.OnConflict
// documentation for more info.
func (u *OpenAIQuotaPeriodUpsertOne) Update(set func(*OpenAIQuotaPeriodUpsert)) *OpenAIQuotaPeriodUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIQuotaPeriodUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetAccountID(v int64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIQuotaPeriodUpsertOne) AddAccountID(v int64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateAccountID() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateAccountID()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetStartedAt(v time.Time) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateStartedAt() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetEndedAt(v time.Time) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateEndedAt() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *OpenAIQuotaPeriodUpsertOne) ClearEndedAt() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.ClearEndedAt()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetResetAt(v time.Time) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateResetAt() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateResetAt()
	})
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *OpenAIQuotaPeriodUpsertOne) ClearResetAt() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.ClearResetAt()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetRequestCount(v int64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *OpenAIQuotaPeriodUpsertOne) AddRequestCount(v int64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateRequestCount() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateRequestCount()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetUsedUsd(v float64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *OpenAIQuotaPeriodUpsertOne) AddUsedUsd(v float64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateUsedUsd() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetUsedPercent sets the "used_percent" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetUsedPercent(v float64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetUsedPercent(v)
	})
}

// AddUsedPercent adds v to the "used_percent" field.
func (u *OpenAIQuotaPeriodUpsertOne) AddUsedPercent(v float64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddUsedPercent(v)
	})
}

// UpdateUsedPercent sets the "used_percent" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateUsedPercent() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateUsedPercent()
	})
}

// SetPredictedQuotaUsd sets the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetPredictedQuotaUsd(v)
	})
}

// AddPredictedQuotaUsd adds v to the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsertOne) AddPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddPredictedQuotaUsd(v)
	})
}

// UpdatePredictedQuotaUsd sets the "predicted_quota_usd" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdatePredictedQuotaUsd() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdatePredictedQuotaUsd()
	})
}

// ClearPredictedQuotaUsd clears the value of the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsertOne) ClearPredictedQuotaUsd() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.ClearPredictedQuotaUsd()
	})
}

// SetSnapshotAt sets the "snapshot_at" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetSnapshotAt(v time.Time) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetSnapshotAt(v)
	})
}

// UpdateSnapshotAt sets the "snapshot_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateSnapshotAt() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateSnapshotAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIQuotaPeriodUpsertOne) SetUpdatedAt(v time.Time) *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertOne) UpdateUpdatedAt() *OpenAIQuotaPeriodUpsertOne {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAIQuotaPeriodUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIQuotaPeriodCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIQuotaPeriodUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAIQuotaPeriodUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAIQuotaPeriodUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAIQuotaPeriodCreateBulk is the builder for creating many OpenAIQuotaPeriod entities in bulk.
type OpenAIQuotaPeriodCreateBulk struct {
	config
	err      error
	builders []*OpenAIQuotaPeriodCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAIQuotaPeriod entities in the database.
func (_c *OpenAIQuotaPeriodCreateBulk) Save(ctx context.Context) ([]*OpenAIQuotaPeriod, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAIQuotaPeriod, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAIQuotaPeriodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAIQuotaPeriodCreateBulk) SaveX(ctx context.Context) []*OpenAIQuotaPeriod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIQuotaPeriodCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIQuotaPeriodCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIQuotaPeriod.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIQuotaPeriodUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIQuotaPeriodCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAIQuotaPeriodUpsertBulk {
	_c.conflict = opts
	return &OpenAIQuotaPeriodUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIQuotaPeriod.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIQuotaPeriodCreateBulk) OnConflictColumns(columns ...string) *OpenAIQuotaPeriodUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIQuotaPeriodUpsertBulk{
		create: _c,
	}
}

// OpenAIQuotaPeriodUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAIQuotaPeriod nodes.
type OpenAIQuotaPeriodUpsertBulk struct {
	create *OpenAIQuotaPeriodCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAIQuotaPeriod.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateNewValues() *OpenAIQuotaPeriodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openaiquotaperiod.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIQuotaPeriod.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAIQuotaPeriodUpsertBulk) Ignore() *OpenAIQuotaPeriodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIQuotaPeriodUpsertBulk) DoNothing() *OpenAIQuotaPeriodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIQuotaPeriodCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAIQuotaPeriodUpsertBulk) Update(set func(*OpenAIQuotaPeriodUpsert)) *OpenAIQuotaPeriodUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIQuotaPeriodUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetAccountID(v int64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *OpenAIQuotaPeriodUpsertBulk) AddAccountID(v int64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateAccountID() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateAccountID()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetStartedAt(v time.Time) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateStartedAt() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetEndedAt(v time.Time) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateEndedAt() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *OpenAIQuotaPeriodUpsertBulk) ClearEndedAt() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.ClearEndedAt()
	})
}

// SetResetAt sets the "reset_at" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetResetAt(v time.Time) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetResetAt(v)
	})
}

// UpdateResetAt sets the "reset_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateResetAt() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateResetAt()
	})
}

// ClearResetAt clears the value of the "reset_at" field.
func (u *OpenAIQuotaPeriodUpsertBulk) ClearResetAt() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.ClearResetAt()
	})
}

// SetRequestCount sets the "request_count" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetRequestCount(v int64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetRequestCount(v)
	})
}

// AddRequestCount adds v to the "request_count" field.
func (u *OpenAIQuotaPeriodUpsertBulk) AddRequestCount(v int64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddRequestCount(v)
	})
}

// UpdateRequestCount sets the "request_count" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateRequestCount() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateRequestCount()
	})
}

// SetUsedUsd sets the "used_usd" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetUsedUsd(v float64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetUsedUsd(v)
	})
}

// AddUsedUsd adds v to the "used_usd" field.
func (u *OpenAIQuotaPeriodUpsertBulk) AddUsedUsd(v float64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddUsedUsd(v)
	})
}

// UpdateUsedUsd sets the "used_usd" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateUsedUsd() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateUsedUsd()
	})
}

// SetUsedPercent sets the "used_percent" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetUsedPercent(v float64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetUsedPercent(v)
	})
}

// AddUsedPercent adds v to the "used_percent" field.
func (u *OpenAIQuotaPeriodUpsertBulk) AddUsedPercent(v float64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddUsedPercent(v)
	})
}

// UpdateUsedPercent sets the "used_percent" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateUsedPercent() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateUsedPercent()
	})
}

// SetPredictedQuotaUsd sets the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetPredictedQuotaUsd(v)
	})
}

// AddPredictedQuotaUsd adds v to the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsertBulk) AddPredictedQuotaUsd(v float64) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.AddPredictedQuotaUsd(v)
	})
}

// UpdatePredictedQuotaUsd sets the "predicted_quota_usd" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdatePredictedQuotaUsd() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdatePredictedQuotaUsd()
	})
}

// ClearPredictedQuotaUsd clears the value of the "predicted_quota_usd" field.
func (u *OpenAIQuotaPeriodUpsertBulk) ClearPredictedQuotaUsd() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.ClearPredictedQuotaUsd()
	})
}

// SetSnapshotAt sets the "snapshot_at" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetSnapshotAt(v time.Time) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetSnapshotAt(v)
	})
}

// UpdateSnapshotAt sets the "snapshot_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateSnapshotAt() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateSnapshotAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIQuotaPeriodUpsertBulk) SetUpdatedAt(v time.Time) *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIQuotaPeriodUpsertBulk) UpdateUpdatedAt() *OpenAIQuotaPeriodUpsertBulk {
	return u.Update(func(s *OpenAIQuotaPeriodUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAIQuotaPeriodUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAIQuotaPeriodCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIQuotaPeriodCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIQuotaPeriodUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
